
function qs(s){return document.querySelector(s)}
function getConfig(){return window.APP_CONFIG||APP_CONFIG}
function getEndpoint(){return getConfig().APPS_SCRIPT_URL||""}
function normalizePhone(v){return String(v||"").replace(/\D/g,"")}
function maskPhone(input){let v=normalizePhone(input.value).slice(0,11);if(v.length<=2){input.value=v;return}if(v.length<=6){input.value=`(${v.slice(0,2)}) ${v.slice(2)}`;return}if(v.length<=10){input.value=`(${v.slice(0,2)}) ${v.slice(2,6)}-${v.slice(6)}`;return}input.value=`(${v.slice(0,2)}) ${v.slice(2,7)}-${v.slice(7)}`}
function nowISO(){return new Date().toISOString()}
function getLocalResponses(){try{return JSON.parse(localStorage.getItem("jogada37_respostas")||"[]")}catch(e){return[]}}
function setLocalResponses(r){localStorage.setItem("jogada37_respostas",JSON.stringify(r))}
function saveLocalResponse(row){const rows=getLocalResponses();rows.push(row);setLocalResponses(rows);return row}
function responseToRow(fd){const c=getConfig();return{id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),evento:c.EVENTO,empresa:c.EMPRESA,data_hora:nowISO(),nome:fd.get("nome")||"",whatsapp:normalizePhone(fd.get("whatsapp")||""),cargo:fd.get("cargo")||"",loja_regiao:fd.get("loja_regiao")||"",sentimento_ia:fd.get("sentimento_ia")||"",preparo_ia:fd.get("preparo_ia")||"",uso_ia:fd.get("uso_ia")||"",desafio_comunicacao:fd.get("desafio_comunicacao")||"",limite_ia:fd.get("limite_ia")||"",jogada37:fd.get("jogada37")||"",aceite_participacao:fd.get("aceite_participacao")?"Sim":"Não",aceite_whatsapp:fd.get("aceite_whatsapp")?"Sim":"Não",origem:"site"}}
function validateForm(form){const d=new FormData(form);const req=["nome","whatsapp","cargo","loja_regiao","sentimento_ia","preparo_ia","uso_ia","desafio_comunicacao","limite_ia","jogada37"];for(const f of req){if(!String(d.get(f)||"").trim())return"Preencha todos os campos obrigatórios antes de enviar."}const phone=normalizePhone(d.get("whatsapp"));if(phone.length<10||phone.length>11)return"Informe um WhatsApp válido com DDD.";if(!d.get("aceite_participacao"))return"Para participar, é necessário concordar com o termo de participação.";return""}
async function postToAppsScript(row){const endpoint=getEndpoint();if(!endpoint){saveLocalResponse(row);return{ok:true,modo:"localStorage"}}const r=await fetch(endpoint,{method:"POST",mode:"cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action:"create",payload:row})});const text=await r.text();let j;try{j=JSON.parse(text)}catch(e){j={ok:r.ok,raw:text}}if(!r.ok||j.ok===false)throw new Error(j.message||"Falha ao salvar resposta.");saveLocalResponse(row);return j}
function initFormPage(){const form=qs("#participationForm");if(!form)return;const phone=qs("#whatsapp");if(phone)phone.addEventListener("input",()=>maskPhone(phone));form.addEventListener("submit",async(e)=>{e.preventDefault();const err=qs("#formError");const btn=qs("#submitBtn");const val=validateForm(form);if(val){err.textContent=val;err.style.display="block";return}err.style.display="none";btn.disabled=true;btn.textContent="Registrando sua Jogada 37...";try{const row=responseToRow(new FormData(form));await postToAppsScript(row);window.location.href="obrigado.html"}catch(ex){err.textContent="Não foi possível enviar agora. Detalhe: "+ex.message;err.style.display="block";btn.disabled=false;btn.textContent="Enviar minha Jogada 37"}})}
function formatSeconds(t){const m=Math.floor(t/60);const s=t%60;return String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")}
function getOrCreateLiveStart(){const k="jogada37_live_start";let v=localStorage.getItem(k);if(!v){v=String(Date.now());localStorage.setItem(k,v)}return Number(v)}
function resetLiveTimer(){localStorage.setItem("jogada37_live_start",String(Date.now()));location.reload()}
async function fetchSummary(){const endpoint=getEndpoint();if(!endpoint)return buildSummary(getLocalResponses());const url=new URL(endpoint);url.searchParams.set("action","summary");url.searchParams.set("t",String(Date.now()));const r=await fetch(url.toString(),{method:"GET",mode:"cors"});const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.message||"Falha ao ler resumo.");return j.summary}
async function fetchRows(){const endpoint=getEndpoint();if(!endpoint)return getLocalResponses();const url=new URL(endpoint);url.searchParams.set("action","list");url.searchParams.set("t",String(Date.now()));const r=await fetch(url.toString(),{method:"GET",mode:"cors"});const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.message||"Falha ao ler respostas.");return j.rows||[]}
function initLivePage(){const timerEl=qs("#timer"),participantsEl=qs("#participantsCount"),playsEl=qs("#playsCount"),statusEl=qs("#liveStatus");if(!timerEl)return;const c=getConfig();const start=getOrCreateLiveStart();function tick(){const elapsed=Math.floor((Date.now()-start)/1000);const rem=Math.max(0,c.TEMPO_QR_SEGUNDOS-elapsed);timerEl.textContent=formatSeconds(rem);if(rem===0){statusEl.textContent="Tempo encerrado. Analisando as jogadas da sala...";timerEl.classList.remove("pulse")}else if(rem<=15){statusEl.textContent="Últimos segundos. O tabuleiro está prestes a mudar.";timerEl.classList.add("pulse")}}async function update(){try{const s=await fetchSummary();participantsEl.textContent=s.totalParticipantes||0;playsEl.textContent=s.totalRespostas||0}catch(e){statusEl.textContent="Modo local ou conexão indisponível. Os dados serão atualizados quando possível."}}tick();update();setInterval(tick,1000);setInterval(update,c.ATUALIZACAO_AO_VIVO_MS||5000);const reset=qs("#resetTimerBtn");if(reset)reset.addEventListener("click",resetLiveTimer)}
const sentimentScores={"Animação":2,"Curiosidade":1,"Neutro":0,"Dúvida":-1,"Cautela":-1,"Preocupação":-2,"Medo":-2}
function mode(v){const c={};v.filter(Boolean).forEach(x=>c[x]=(c[x]||0)+1);let b="",n=0;Object.entries(c).forEach(([k,q])=>{if(q>n){b=k;n=q}});return b||"-"}
function average(v){const nums=v.map(Number).filter(n=>!Number.isNaN(n));if(!nums.length)return 0;return nums.reduce((a,b)=>a+b,0)/nums.length}
function countBy(v){const c={};v.filter(Boolean).forEach(x=>c[x]=(c[x]||0)+1);return c}
function buildSummary(rows){const total=rows.length;const uniquePhones=new Set(rows.map(r=>r.whatsapp).filter(Boolean));const sv=rows.map(r=>r.sentimento_ia);const avg=average(sv.map(v=>sentimentScores[v]??0));let reading="neutro";if(avg>=1)reading="positivo";if(avg>0&&avg<1)reading="curioso com cautela";if(avg<0&&avg>-1)reading="cauteloso";if(avg<=-1)reading="preocupado";const preparoNums=rows.map(r=>Number(r.preparo_ia)).filter(n=>!Number.isNaN(n));const preparados=preparoNums.filter(n=>n>=4).length;const percPrep=preparoNums.length?Math.round((preparados/preparoNums.length)*100):0;return{totalParticipantes:uniquePhones.size||total,totalRespostas:total,sentimentoPredominante:mode(sv),sentimentoMedio:Number(avg.toFixed(2)),leituraSentimento:reading,mediaPreparo:Number(average(rows.map(r=>r.preparo_ia)).toFixed(2)),percentualPreparados:percPrep,principalUsoIA:mode(rows.map(r=>r.uso_ia)),principalDesafio:mode(rows.map(r=>r.desafio_comunicacao)),principalLimite:mode(rows.map(r=>r.limite_ia)),porSentimento:countBy(sv),porUsoIA:countBy(rows.map(r=>r.uso_ia)),porDesafio:countBy(rows.map(r=>r.desafio_comunicacao)),porLimite:countBy(rows.map(r=>r.limite_ia)),respostasAbertas:rows.map(r=>r.jogada37).filter(Boolean)}}
function renderCard(id,value){const el=qs(id);if(el)el.textContent=value??"-"}
function escapeHtml(v){return String(v||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function renderBars(id,counts){const cont=qs(id);if(!cont)return;const entries=Object.entries(counts||{}).sort((a,b)=>b[1]-a[1]);const max=entries.length?Math.max(...entries.map(e=>e[1])):1;cont.innerHTML=entries.map(([l,c])=>{const pct=Math.round((c/max)*100);return `<div class="bar-item"><div class="bar-label"><span>${escapeHtml(l)}</span><strong>${c}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${pct}%"></div></div></div>`}).join("")||"<p class='small'>Sem dados ainda.</p>"}
function renderOpenAnswers(id,answers){const cont=qs(id);if(!cont)return;cont.innerHTML=(answers||[]).slice(-12).reverse().map(a=>`<div class="callout">${escapeHtml(a)}</div>`).join("")||"<p class='small'>Ainda não há respostas abertas.</p>"}
async function initResultPage(){if(!qs("#resultPage"))return;async function load(){try{const s=await fetchSummary();renderCard("#totalParticipantes",s.totalParticipantes);renderCard("#totalRespostas",s.totalRespostas);renderCard("#sentimentoPredominante",s.sentimentoPredominante);renderCard("#leituraSentimento",s.leituraSentimento);renderCard("#mediaPreparo",s.mediaPreparo||0);renderCard("#percentualPreparados",(s.percentualPreparados||0)+"%");renderCard("#principalUsoIA",s.principalUsoIA);renderCard("#principalDesafio",s.principalDesafio);renderCard("#principalLimite",s.principalLimite);renderBars("#barsSentimento",s.porSentimento);renderBars("#barsUsoIA",s.porUsoIA);renderBars("#barsDesafio",s.porDesafio);renderBars("#barsLimite",s.porLimite);renderOpenAnswers("#openAnswers",s.respostasAbertas)}catch(e){const box=qs("#resultError");if(box){box.textContent="Não foi possível carregar os resultados: "+e.message;box.style.display="block"}}}load();setInterval(load,10000)}
function rowsToCsv(rows){const headers=["id","evento","empresa","data_hora","nome","whatsapp","cargo","loja_regiao","sentimento_ia","preparo_ia","uso_ia","desafio_comunicacao","limite_ia","jogada37","aceite_participacao","aceite_whatsapp","origem"];const lines=[headers.join(";")];rows.forEach(row=>{lines.push(headers.map(h=>`"${String(row[h]??"").replaceAll('"','""')}"`).join(";"))});return lines.join("\n")}
function downloadText(filename,content){const blob=new Blob([content],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
async function initAdminPage(){const login=qs("#adminLogin"),panel=qs("#adminPanel");if(!login||!panel)return;const pass=qs("#adminPassword"),btn=qs("#adminLoginBtn"),err=qs("#adminError");function show(){login.style.display="none";panel.style.display="block";loadAdminRows()}if(sessionStorage.getItem("jogada37_admin_ok")==="1")show();btn.addEventListener("click",()=>{if(pass.value===getConfig().SENHA_ADMIN){sessionStorage.setItem("jogada37_admin_ok","1");show()}else{err.textContent="Senha inválida.";err.style.display="block"}});qs("#refreshAdminBtn").addEventListener("click",loadAdminRows);qs("#exportCsvBtn").addEventListener("click",async()=>downloadText("respostas_jogada37.csv",rowsToCsv(await fetchRows())));qs("#clearLocalBtn").addEventListener("click",()=>{if(confirm("Deseja limpar apenas as respostas locais deste navegador?")){localStorage.removeItem("jogada37_respostas");loadAdminRows()}})}
async function loadAdminRows(){const body=qs("#adminTableBody"),total=qs("#adminTotal");if(!body)return;try{const rows=await fetchRows();total.textContent=rows.length;body.innerHTML=rows.slice().reverse().map(r=>`<tr><td>${escapeHtml(r.data_hora)}</td><td>${escapeHtml(r.nome)}</td><td>${escapeHtml(r.whatsapp)}</td><td>${escapeHtml(r.cargo)}</td><td>${escapeHtml(r.loja_regiao)}</td><td>${escapeHtml(r.sentimento_ia)}</td><td>${escapeHtml(r.preparo_ia)}</td><td>${escapeHtml(r.uso_ia)}</td><td>${escapeHtml(r.desafio_comunicacao)}</td><td>${escapeHtml(r.limite_ia)}</td><td>${escapeHtml(r.jogada37)}</td></tr>`).join("")||"<tr><td colspan='11'>Sem respostas ainda.</td></tr>"}catch(e){body.innerHTML=`<tr><td colspan="11">Erro ao carregar: ${escapeHtml(e.message)}</td></tr>`}}
document.addEventListener("DOMContentLoaded",()=>{initFormPage();initLivePage();initResultPage();initAdminPage()})
